name: test_trigger
on: 
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo sha
        run: echo "SHA=${{ github.event.client_payload.sha }}"

      - name: Checkout  
        uses: actions/checkout@v3 

      - name: cat ui values
        run: cat deploy/values-ui.yaml.gotmpl

      - name: write new image tag to ui
        run: yq -i ".image.tag = \"locan-env-sha-${{ github.event.client_payload.sha }}\"" deploy/values-ui.yaml.gotmpl

      - name: cat ui values
        run: cat deploy/values-ui.yaml.gotmpl

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
          git add .
  
          git commit -m 'files changed'
          
          git push
