name: test_trigger
on: 
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo sha
        run: echo "SHA=${{ github.event.client_payload.sha }}"

      - name: Checkout  
        uses: actions/checkout@v3 

      - name: ls
        run: ls

      - name: cat ui values
        run: cat deploy/values-ui.yaml.gotmpl
